site_name: Automata Network Docs
site_url: https://docs.ata.network
site_description: Automata Network Documentation
site_author: Automata Team

repo_url: https://github.com/automata-network/docs

nav:
  - Welcome: index.md
  - The MEV Wiki:
    - Introduction: ./mev/introduction.md
    - Resource List: ./mev/resource-list.md
    - Terms and Concepts: ./mev/terms-and-concepts.md
    - Examples: ./mev/examples.md
    - Attempts to Trick the Bots: ./mev/trick-the-bots.md
    - Solutions:
      - Different Approaches: ./mev/solutions/approaches.md
      - FaaS or MEVA: ./mev/solutions/faas-or-meva.md
      - MEV Minimization / Prevention:  ./mev/solutions/mev-minimization-prevention.md
      - Others: ./mev/solutions/others.md
    - Miscellaneous: ./mev/misc.md
  - Witness: ./guide/witness-get-started.md

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - tabs
    - instant
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.top
    - navigation.tabs
    - toc.integrate
    - navigation.expand
  logo: "assets/favicon-192.png"
  favicon: "assets/favicon.ico"

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/automata-network
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/automatanetwork
    - icon: fontawesome/brands/medium
      link: https://medium.com/@automatanetwork
    - icon: fontawesome/brands/telegram
      link: https://t.me/ata_network
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/Us8cxTVRxG

copyright: Copyright &copy; 2021 Automata Network
