site_name: Automata Docs
site_url: https://docs.ata.com
site_description: Automata Documentation
site_author: Automata Team

repo_url: https://github.com/automata-network/docs

nav:
  - Home: index.md
  - Guide: ./guide/witness-get-started.md


theme:
  name: material
  font: false
  palette:
    primary: black
  features:
      - tabs
      - instant
  logo: 'assets/favicon-192.png'
  favicon: 'assets/favicon.ico'

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/automatanetwork
      name: Automata on Twitter
    - icon: fontawesome/brands/medium
      link: https://medium.com/@automatanetwork
      name: Automata on medium
    - icon: fontawesome/brands/github
      link: https://github.com/automata-network