site_name: Automata Documentation
site_url: https://docs.ata.network
site_description: Automata Documentation
site_author: Automata Team

repo_url: https://github.com/automata-network/docs

nav:
  - Home: index.md
  - Guide: ./guide/witness-get-started.md

theme:
  name: null
  custom_dir: 'cinder'
  colorscheme: dracula
  disable_nav_search: true
  disable_footer: true
  highlightjs: true
  hljs_languages:
    - yaml

markdown_extensions:
  - admonition